/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paqueteprincipal;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebastian JB
 */
public class ventanaprincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaprincipal
     */
    public ventanaprincipal() {
        
        initComponents();
        configuracionVentana();
    }

    public void configuracionVentana() {
        
        this.setSize(800, 600);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInterno = new javax.swing.JDesktopPane();
        barraMenus = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        MenuArchivoAbrir = new javax.swing.JMenuItem();
        MenuArchivoCerrar = new javax.swing.JMenuItem();
        MenuCerrarTodo = new javax.swing.JMenuItem();
        MenuInfo = new javax.swing.JMenuItem();
        separador1 = new javax.swing.JPopupMenu.Separator();
        MenuArchivoSalir = new javax.swing.JMenuItem();
        MenuVentana = new javax.swing.JMenu();
        MenuCascada = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelInternoLayout = new javax.swing.GroupLayout(panelInterno);
        panelInterno.setLayout(panelInternoLayout);
        panelInternoLayout.setHorizontalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelInternoLayout.setVerticalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        getContentPane().add(panelInterno, java.awt.BorderLayout.CENTER);

        MenuArchivo.setText("Archivo");

        MenuArchivoAbrir.setText("Abrir");
        MenuArchivoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuArchivoAbrirActionPerformed(evt);
            }
        });
        MenuArchivo.add(MenuArchivoAbrir);

        MenuArchivoCerrar.setText("Cerrar");
        MenuArchivoCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuArchivoCerrarActionPerformed(evt);
            }
        });
        MenuArchivo.add(MenuArchivoCerrar);

        MenuCerrarTodo.setText("Cerrar Todo");
        MenuCerrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCerrarTodoActionPerformed(evt);
            }
        });
        MenuArchivo.add(MenuCerrarTodo);

        MenuInfo.setText("Info");
        MenuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInfoActionPerformed(evt);
            }
        });
        MenuArchivo.add(MenuInfo);
        MenuArchivo.add(separador1);

        MenuArchivoSalir.setText("Salir");
        MenuArchivo.add(MenuArchivoSalir);

        barraMenus.add(MenuArchivo);

        MenuVentana.setText("Ventana");

        MenuCascada.setText("Cascada");
        MenuCascada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCascadaActionPerformed(evt);
            }
        });
        MenuVentana.add(MenuCascada);

        barraMenus.add(MenuVentana);

        setJMenuBar(barraMenus);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuArchivoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuArchivoAbrirActionPerformed
        
        JFileChooser abrir = new JFileChooser();
        
        int boton = abrir.showOpenDialog(null);
        
        if (boton == JFileChooser.APPROVE_OPTION) {
            ventanainterna vi = new ventanainterna();
            vi.setResizable(true);
            vi.setMaximizable(true);
            vi.setIconifiable(true);
            vi.setClosable(true);

            panelInterno.add(vi);

            String camino = abrir.getSelectedFile().toString();
            vi.setImagen(camino);
            vi.setTitle(camino);
            vi.setVisible(true);
        }
        
    }//GEN-LAST:event_MenuArchivoAbrirActionPerformed

    private void MenuArchivoCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuArchivoCerrarActionPerformed
        
        ventanainterna vactiva = (ventanainterna) panelInterno.getSelectedFrame();
        if(vactiva!=null){
            vactiva.dispose();
        }
    }//GEN-LAST:event_MenuArchivoCerrarActionPerformed

    private void MenuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInfoActionPerformed
        // TODO add your handling code here:
        ventanainterna vactiva = (ventanainterna) panelInterno.getSelectedFrame();
         if(vactiva!=null){
           
            String titulo = vactiva.getTitle();
            
            JOptionPane.showMessageDialog(null,"Camino de la imagen:\n"+titulo);
         }
         else{
            JOptionPane.showMessageDialog(null,"No hay ninguna imagen seleccionada");
        }
    }//GEN-LAST:event_MenuInfoActionPerformed

    private void MenuCerrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCerrarTodoActionPerformed
       
        int i;
        JInternalFrame v[] = panelInterno.getAllFrames();
        
        for(i=0;i<v.length;i++){
            v[i].dispose();
        }
        
    }//GEN-LAST:event_MenuCerrarTodoActionPerformed

    private void MenuCascadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCascadaActionPerformed
        // TODO add your handling code here:
      
        int i;
        int x,y;
        
        JInternalFrame v[] = panelInterno.getAllFrames();
    
        x=0;
        y=0;
        
        for(i=v.length-1;i>=0;i--){
            v[i].setSize(600,400);
            v[i].setLocation(x,y);
            x=x+30;
            y=y+30;
          
            
        }
    }//GEN-LAST:event_MenuCascadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenuItem MenuArchivoAbrir;
    private javax.swing.JMenuItem MenuArchivoCerrar;
    private javax.swing.JMenuItem MenuArchivoSalir;
    private javax.swing.JMenuItem MenuCascada;
    private javax.swing.JMenuItem MenuCerrarTodo;
    private javax.swing.JMenuItem MenuInfo;
    private javax.swing.JMenu MenuVentana;
    private javax.swing.JMenuBar barraMenus;
    private javax.swing.JDesktopPane panelInterno;
    private javax.swing.JPopupMenu.Separator separador1;
    // End of variables declaration//GEN-END:variables
}
